CREATE TABLE IF NOT EXISTS quantity_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_value DOUBLE PRECISION NOT NULL,
    second_value DOUBLE PRECISION NOT NULL,
    first_unit VARCHAR(50) NOT NULL,
    second_unit VARCHAR(50),
    measurement_type VARCHAR(50) NOT NULL DEFAULT 'unknown',
    operation VARCHAR(50) NOT NULL,
    result VARCHAR(100),
    success BOOLEAN NOT NULL,
    error_message VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quantity_measurement_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measurement_id BIGINT NOT NULL,
    operation VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    detail VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quantity_measurement_history_measurement
        FOREIGN KEY (measurement_id)
        REFERENCES quantity_measurements(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_quantity_measurements_operation
    ON quantity_measurements(operation);

CREATE INDEX IF NOT EXISTS idx_quantity_measurements_type
    ON quantity_measurements(measurement_type);
