app.repository=database
app.env=dev

database.url=jdbc:h2:./target/quantity-measurements;MODE=LEGACY;AUTO_SERVER=FALSE
database.username=sa
database.password=
database.pool.initialSize=2
database.pool.maxSize=8
database.pool.timeoutMillis=3000

dev.database.url=jdbc:h2:./target/quantity-measurements-dev;MODE=LEGACY;AUTO_SERVER=FALSE
dev.database.username=sa
dev.database.password=

test.database.url=jdbc:h2:mem:quantity_measurement_test;DB_CLOSE_DELAY=-1;MODE=LEGACY
test.database.username=sa
test.database.password=

logging.level=INFO
